### PR TITLE
ct_expand-maps: support maps in ct_expand:term/1

### PR DESCRIPTION
**Pull request by fenollp**
Fixes https://github.com/uwiger/parse_trans/issues/23

### CODE REVIEW

**Comment by uwiger** [comment]
Hmm... `parse_trans` has no current dependency to `jsx`, but it's in `examples/`, which should be ok. Also, I like the example.

However, if you simply cd to `examples/` and type `make`, compilation will break until you manually fetched `jsx`. This should be documented, at a minimum, or addressed in `examples/Makefile`.

**Comment by fenollp** [comment]
Hm I thought examples/ were not really ready for compilation, just to show the idea.
What lead me to believe that is you can't `make test -C examples/` due to [this util file being missing.](https://github.com/uwiger/parse_trans/blob/93a24451ab5d64bc009f7696bf807ec15f92ad75/examples/Makefile#L9)

Not sure how to add a test-time dependency on jsx with rebar2... What about I just mock the jsx call (replace it with something along `json_decode("bla.json") -> (maps:from_list([]))#{<<"k">> => [42]}.`)?

**Comment by uwiger** [comment]
Yeah, `examples` really should evolve into something testable, but I've been too lazy to do it. ;-)

**Comment by fenollp** [comment]
Updated. I can squash if you want.

**Comment by uwiger** [comment]
That's ok. Merged. Thanks.

**Comment by fenollp** [comment]
Thank you :) Could you publish on https://hex.pm/packages/parse_trans ?

**Comment by uwiger** [comment]
Done, version 3.1.0

**Pull request merged**
