### PR TITLE
otp21: adapt get_stacktrace calls for OTP21

### PR DESCRIPTION
**Pull request by fenollp**
Since a fix for #28 is coming up in final version of OTP 21 this month let's fix the compilation warnings ahead of time.

Said warnings:
```erlang
===> Verifying dependencies...
===> Compiling parse_trans
src/parse_trans.erl:129: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
src/parse_trans.erl:326: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
src/parse_trans.erl:346: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
src/parse_trans.erl:737: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
src/parse_trans.erl:868: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
src/parse_trans.erl:874: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
src/parse_trans.erl:874: Warning: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace

```

Note: I can move the line endings of all files from DOS to just `\n` with a simple command. Want me to open a PR with that? It would make `git blame` harder though.

### CODE REVIEW

**Comment by ferd** [comment]
@uwiger any way to get this merged & on hex?

**Comment by getong** [comment]
@fenollp I make a pr on your branch, and I think use OTP_REALSESE macro is much better. 
fenollp/parse_trans#1 , use it if you like it.

**Comment by uwiger** [comment]
Sorry about the delay. It looks good, but I haven't had time to test it yet. I could merge on good faith, of course ... :-/

**Comment by fenollp** [comment]
Maybe it’s time to activate some free CI service ;)

**Comment by fenollp** [comment]
@uwiger added a commit that adds TravisCI that just runs a compilation step. I ruled out R15 & R16 as these don't build.

You can see the build passing at https://travis-ci.org/fenollp/parse_trans/builds/403457699

I can bump the app's version if that's easier to publish to hex for you :)

**Comment by fenollp** [comment]
Tests pass!

**Comment by uwiger** [comment]
Thanks!

**Comment by uwiger** [comment]
Tagged with version 3.3.0 and published to hex

**Pull request merged**
