### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by vkatsuba**
[CI Result](https://github.com/vkatsuba/parse_trans/actions)

### CODE REVIEW

**Comment by uwiger** [comment]
Nice, but the README file is actually generated using edown from [doc/overview.edoc](/uwiger/parse_trans/blob/master/doc/overview.edoc).

**Comment by vkatsuba** [comment]
Ops... missed it... will fix it soon

**Comment by vkatsuba** [comment]
Done.

**Comment by uwiger** [comment]
Hehe, this reminds me that the `edown` dependency needs to be updated (to 0.8.4) for `rebar3 edoc` to even work with current OTP versions. This will rebuild docs with lots of warnings, but that can be addressed in a later PR. :)

**Comment by uwiger** [comment]
Anyway, the edown build worked with the new version.

**Comment by uwiger** [comment]
Made a few tweaks and updated docs on master. Thanks.

**Pull request merged**
