### PR TITLE
switching to Erlang/OTP 18.0 compatible version of edown

### PR DESCRIPTION
**Pull request by odo**
Or maybe even better: add a new tag to the updated edown repo end reference this.
Thanks!

### CODE REVIEW

**Comment by uwiger** [comment]
I tagged the latest edown master as 0.7

**Comment by uwiger** [comment]
If you could update the PR, I'll merge.

**Comment by odo** [comment]
Done.

**Comment by uwiger** [comment]
Thanks. Merged.

**Comment by uwiger** [comment]
Tagged as 2.9.2

**Pull request merged**
