### PR TITLE
[WIP] Add support for maps

### PR DESCRIPTION
**Pull request by filmor**

### CODE REVIEW

**Comment by uwiger** [comment]
Nice!

Could you also update the example code in the edoc part (starting on line 44)?

**Comment by filmor** [comment]
Hmm, what do I need to tell `erlc` such that it runs the parse transform but keeps record invocations around?

**Comment by uwiger** [comment]
Excellent! That was long overdue, apparently. :)

Merged. Thanks.

**Comment by uwiger** [comment]
> Hmm, what do I need to tell erlc such that it runs the parse transform but keeps record invocations around?

What do you mean?

**Comment by uwiger** [comment]
(perhaps you can ask the question in an issue?)

**Comment by filmor** [comment]
If you compare the `edoc` parts before and after this PR you see, that `R#t.a` got converted to `case R of {t, _, A, _} -> A; _ -> error({badrecord, t}) end`, how did you create this before=

**Comment by uwiger** [comment]
Ah, ok. I think there is room for some PRs that make the generated code more beautiful and efficient. :)

Also, I'm thinking that it might be good to have an option to limit what types of accessors are generated. Not all people might be interested in lens accessors, for example.

**Pull request merged**
